### ISSUE TITLE
Frontend: Member list needs a redesign

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/storyden#214]
Currently looks like this... yikes

![image](https://github.com/user-attachments/assets/c5fe00d1-38d0-4d15-a46f-c40873e9ce6f)

It should instead use a `<CardBox>` component for each row with the `<MemberBadge>` component for the actual avatar/name.

The "Sign up date" should be presented in a nicer way to...

OR...

use `<Table>` from ParkUI because I can imagine that long-term, this will start to look more like Discord with more information being displayed:

![image](https://github.com/user-attachments/assets/9c5a1337-b5fd-446a-8af3-aa8af4ff26f6)

**Comment by Southclaws** [comment]
hard parts with tables is making it responsive... but it's probably the best way to go. Some columns can be display: none if mobile and the additional info could be selectively shown in the first cell. Resulting in the mobile version probably resembling cards anyway.

**Comment by Southclaws** [comment]
Also needed at some point: filtering, sorting, etc.

Mostly for admins

**Comment by mashazyu** [comment]
@Southclaws, hi,

I'd like to work on this issue, if it's still available.

**Comment by Southclaws** [comment]
Hey @mashazyu that's amazing to hear! Let me know if you need any guidance for this, I'll avoid touching this area of the codebase so you don't need to deal with any rebase conflicts.

**Comment by mashazyu** [comment]
@Southclaws 

, hello!

Thank you for the opportunity to work on the issue. I appreciate your trust in me to contribute to the project. However, due to personal reasons, I regret to inform you that I will not be able to continue working on this task.
I apologize for any confusion this may cause, and I kindly ask if you could unassign me from the issue.
Thank you for your understanding!

**Comment by Southclaws** [comment]
No problem at all, thank you!
