### ISSUE TITLE
WebAuthN no feedback on incorrect registration attempts.

### ISSUE THREAD

**Issue by Bios-Marcel** [Southclaws/storyden#46]
When trying to register with WebAuthN, even though already registered, you are prompted for authentification and then the page just redirects to the homepage. Trying to use password on the same account will return "wrong login method" (or so).

**Comment by Southclaws** [comment]
Two problems identified here:
1. there was a missing await on `passkeyRegister` call - fixed here: https://github.com/Southclaws/storyden/commit/33cb5e7f68625e092479a3f29c173a18d6e6d652
2. when the credential is requested to be created via a call to `/api/v1/auth/webauthn/make/<handle>` this endpoint actually makes no attempt to check if the handle is already taken, it constructs a `PublicKeyCredentialCreationOptions` object and responds in order to allow the browser to continue the signing process and only when the second call comes to `/v1/auth/webauthn/make` with the `PublicKeyCredential` object signed by the client does the Storyden server actually attempt to create the account and fails.

Obviously a pretty silly oversight on my part, the first call should respond with a 409 Conflict response which:
1. cancels your browser's Passkey flow
2. informs you the username is taken via the input form error text

Thanks for reporting the issue, will get a fix out right away!

**Comment by Southclaws** [comment]
![image](https://github.com/Southclaws/storyden/assets/1636971/b90fc003-2a3d-4910-a69a-133eca14a8d8)

Seems like I already thought of this 😅
