### ISSUE TITLE
Adding photos bugs out (and converts photo post to link post)

### ISSUE THREAD

**Issue by dennorske** [Southclaws/storyden#52]
Making a new post, with category selected as "photos", I added three photos that I uploaded from my computer.

There are two issues:

1. Adding photos converts them to asset links in the post, which again converts my post type from `Photos` --> `Links`
2. Dragging photos in to the editor box is flaky. It happens to be flickering, and i need to exit the box and quickly drag my mouse in to the box again for it to let me release the photos properly. Otherwise the browser handles the drop and opens a new tab.

Gif of the dragging issue;
![Gif showing issue 1](https://pics.ducky.rocks/images/2023/11/28/18bb611c8fd05ef55fb5f92376fa3ec2.gif)

Also, if you only add one photo to a photo post, the post (when it is converted to a URL post by itself, see 1.), the URL that appears directs to new.computer, which most likely is the first link you posted on storyden.
<img width="896" alt="image" src="https://github.com/Southclaws/storyden/assets/3287543/2413744f-fa29-4b11-8e83-c5c852a5ead4">

**Comment by Southclaws** [comment]
So there were a few things happening here that caused this annoying bug, here's a short summary:

https://github.com/Southclaws/storyden/pull/55/files#diff-38ac3d86826dd99429697a88e7b7ca49e96800e6c8ddbf084662acfef0e4c1beR56-R59

Fetch allowed empty URLs which broke the query in stale revalidation. Basically, when a link is submitted to be hydrated, Fetch will do a HTTP get on the URL but before this happens, it checks if the URL is already present in the DB and returns that data if so. Afterwards, it'll asynchronously fetch new data to keep the URL's data up to date.

But the calling code was allowing empty URLs to slip in.

https://github.com/Southclaws/storyden/pull/55/files#diff-069999be17941048f762ae3ed913fb4b23c3cd3f736dea8c317cb4761e95e7c1R98

The link order matters here, each post (or cluster or item, basically any form of content) may contain zero or many links, not just one. Because a piece of content may have multiple sources, a product may have multiple store pages, etc. but the _first_ link in the list is special, that's the link that's shown at the top of the post and in the feed.

I really should change this though, instead of a list with the first item being special, I need to simply add another column to the "Post" schema that's like the "primary_link" or something.

Anyway, url = "" means the select query found everything and picked the first. That's why `new.computer`'s link appeared as the primary link of all new posts!

The second one was simpler, this was just my shoddy markdown tree walking code trying to parse out links from `ast.Text` nodes instead of just using `ast.Link` nodes which already do that bit.

Also included in that patch were a couple of fixes:
- another bug caused threads to not get updated fully when dragging in an image, this caused unexpected unsaved content when you hit publish due to the content not being saved properly https://github.com/Southclaws/storyden/pull/55/files#diff-274aefb7a37b8a62b1227194dae2063a3a58e46daac8a26013e7b3fabcaebfa0R72-R79
- when editing posts in the thread view, they now update live as expected (without needing a page refresh) https://github.com/Southclaws/storyden/pull/55/files#diff-38b102a3d0f0fe75891aa8d7f4f6fe28e78ad3ab45b5412c3cd9b3e951ed235aR45
